# Generated by Django 3.2.6 on 2021-08-31 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(blank=True, null=True, verbose_name='%Y-%m-%d %H:%M:%S')),
                ('payment_type', models.CharField(choices=[('Credit Card', 'Credit Card')], default='Credit Card', max_length=11)),
                ('paid_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(max_length=3, null=True)),
                ('is_booked', models.BooleanField(default=False)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.booking')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.show')),
            ],
            options={
                'unique_together': {('seat_number', 'show')},
            },
        ),
    ]
